# Autogenerated wrapper script for Exafmmt_jll for i686-linux-gnu-cxx11-march+prescott
export libExafmm32, libExafmm64

using CompilerSupportLibraries_jll
using libblastrampoline_jll
using FFTW_jll
JLLWrappers.@generate_wrapper_header("Exafmmt")
JLLWrappers.@declare_library_product(libExafmm32, "libExafmm32.so")
JLLWrappers.@declare_library_product(libExafmm64, "libExafmm64.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll, FFTW_jll)
    JLLWrappers.@init_library_product(
        libExafmm32,
        "lib/libExafmm32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libExafmm64,
        "lib/libExafmm64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
